### ISSUE TITLE
about mentornet

### ISSUE THREAD

**Issue by zhaoxin94** [thexp/thexp-implement#1]
Thanks a lot for your code!

I want to use your Pytorch implementation of mentornet. So, I want to know whether your implementation is a completed one and with no bugs!

**Comment by sailist** [comment]
Sorry, the detail of `mentornet`(used to output weight of loss)  is still not implemented, other training procedure is finished, you can complete mentornet by the official repository.

**Comment by sailist** [comment]
I give up reimplementing mentormix, but I succefully finished reproducing the result of the current sota paper in label correction(noisy label): **Distilling Effective Supervision from Severe Label Noise (IEG)**, you can see README.md and code for details.

But in fact, I am a little desperated now, I started my deeplearning study from semisupervised to noisy label, and each sota results were reached by Google, and the accuracy seems so high that can't get higner in a period of time.
