### ISSUE TITLE
想在自己的数据上训练，需要改哪些地方呢

### ISSUE THREAD

**Issue by PyJulie** [thexp/thexp-implement#2]
继承的类有点多，我调了好多次还是有bug

**Comment by sailist** [comment]
通过重写 `Trainer.datasets()` 方法构建自己的数据集，构建和注册 `DataLoader` 的方式可以参考 `trainers/mixin/datasets.py` 下的各个 `mixin` 类的写法。

此外，推荐通过多继承方式将 数据集、模型、Loss计算函数分开构建，方便重用。

thexp 由于封装比较多，因此需要有一定 Python 基础，和一定的学习成本
